### ISSUE TITLE
Add selection to fixed color

### ISSUE THREAD

**Issue by arscdev** [456ken/Highlighter-vscode#18]
Thank you for this great extension. I have one enhancement that would make adding keywords to different colors much faster. It should be possible to add a selection to a fixed color by command or shortcut.

For example:

CTRL+1 = Add selection to color green
CTRL+2 = Add selection to color red
CTRL+3 = Add selection to color cyan

If the color doesn't exist, it should be added to the keyword list.
If the selection exists in the color, it should be deleted.
If the selection exists in a different color, it should be remove from the old color.

**Comment by 456ken** [comment]
Thank you for the good rating and needs.
I will implement it in the next update.

**Comment by arscdev** [comment]
That sounds good.

**Comment by 456ken** [comment]
note.
Shortcut is enabled only when the text is selected.
```json
{
  "key": "ctrl+1",
  "command": "mch.ToggleColor.red",
  "when": "editorHasSelection"
}
```

**Comment by arscdev** [comment]
I think that makes sense.

**Comment by arscdev** [comment]
Thank you. Works perfect.

**Comment by 456ken** [comment]
Thank you too. Please let me know if you have any problems.
