### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by oxk4r01** [456ken/Highlighter-vscode#29]
Hi! Would it be possible to edit the highlights transparency?
Regards, andt hanks a lot for the extension, I find it really usefull :)

**Comment by 456ken** [comment]
Hi oxk4r01! Thanks for the question.

Its option is able to change by 'Settings > Extensions > MultiColorHighlighter > Brightness: Dark or Light'.
The two options 'Dark / Light' depend on the brightness of VSCode theme.
